### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#1]
# Motivation
Setup NextJS project with express server.

# Tasks
- [x] Import dependencies (Use my website as a template)
- [x] get the basic NextJS configuration up.
- [x] Be able to run example on heroku.
