### ISSUE TITLE
Explore Preact Optimization

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#12]
# Motivation
We want to see if we want optimize the application even further by using Preact instead of React.

# Task Implementation
- [x] Use my example Repo of First Preact App.
- [x] Replace all React headers with Preact.
- [x] Import Preact and Preact dependencies.
- [x] Be able to build the application.
- [x] Find a way to get around modals not working in preact.
- [x] Be able to render the expander list in Preact.
- [x] Be able to associate an icon for reach server.
- [x] Be able to open and close the expander menu.
- [x] Deploy to Heroku.
