### ISSUE TITLE
User can add id's to an access list

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#14]
# Motivation
We want to be able to add ID's to a contact list.

# Task Implementation
- [ ] Hook up heroku PSQL to arch
- [ ] Be able to connect to database in new system.
- [ ] Create a form to add an ID.
- [ ] Create validation around the form so that only a numerical ID can be added.
- [ ] Check that the ID was successfully added to the database.
- [ ] Handle the case where the ID was already in the system but added again.
