### ISSUE TITLE
Replace LocalStorage with Cookies

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#21]
# Motivation
We want to replace the localStorage with Cookies which are part of the HTTP standard.

# Tasks
- [ ] Read up on cookies
- [ ] Replace the localStorage lines with cookie access.
- [ ] Create a generic method to read cookies and parse them.
- [ ] Import cookie parser for express.
- [ ] Be able to process cookies on the backend.
