### ISSUE TITLE
Be able to Authenticate through Discord

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#3]
# Motivation
We want to be able to authenticate through discord. We start this by using the OAUTH2 routine followed by saving the user's credentials through localStorage and saving it in the database.

# Task Implementation
- [x] Import Semantic-UI-React
- [x] Be able to see the material-ui components on the server.
- [x] Create a function that handles logging in.
- [x] Be able to create a button to start the OAUTH2 routine.
- [x] Be able to successfully grant a token.
- [x] Be able to successfully tell the user they have logged in.
