### ISSUE TITLE
Be able to persist a user session

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#5]
# Motivation
Now that we can get back an access token from the discord on the user client, we want to be sure that we can save the user's session on a database as well as on the client so that the user can persist their session. 

# Task Implementation
- [x] Get a database over the sever connection.
- [x] On a successful login, do not return the raw access token. Instead return a hash and a userId associated with that hash.
- [x] Store the hash and userId in an auth pair on postgres.
- [x] Be able to verify that the user is the correct one.
- [x] Be able to if the localstorage values are populated, to use that as authentication.
- - [x] Addendum: Establish a priority order that if there isn't a code and a localstore is populated with values, use that. Otherwise the code in the URL comes first as the user session.
