### ISSUE TITLE
User can Log Out

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#7]
# Motivation
Now that we can persist a user session, we want to be able to log out of the user's session. This will be accomplished by deleting the saved session on the client, deleting the authorization from discord, and finally deleting the authorization record from the database.

# Tasks
- [x] Create a hook to be able to detect if the user wants to log out.
- [x] Be able to validate the hook dependencies.
- [x] Be able to validate remove the localStorage credentials
- [x] Create an API route to handle deletion of authorization.
- [x] Request to discord to remove authorization.
- [x] Delete the associated rows from the database that the user is associated with.
- [x] When all is said and done, take the user back to the origin page.
