### ISSUE TITLE
User can see User and Server Information

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/dbot#9]
# Motivation
Now that we can login, persist a user session, along with being able to logout, we want to be able to see the user's information about what servers they are on as well as some other information from the user such as pictures and username.

# Task Implementation
- [x] On Login, be able to create a list of the servers the user is in.
- [x] On Login, be able to create an icon that renders the user's avatar if they have one. Otherwise just render a blank avatar.
- [x] Have the username be displayed next to the icon.
- [x] Be able to get a list of servers from the discord API.
- [x] Be able to render the list of servers from the discord API via dropdown menu.
